### ISSUE TITLE
Command to make the bot add you as an osu friend

### ISSUE THREAD

**Issue by tylerscheuble** [jerwuqu/osusoloq#10]
This is for people who have mutual messages only enabled so they can use the bot without having to disable the setting.

**Comment by jonese1234** [comment]
This will be hard i think, also a program that auto added people as friends was banned by ppy a while ago, also there is a friend limit, how to deal with this! it would be best to manualy add i think

**Comment by tylerscheuble** [comment]
I agree. We should just do this on request.
